name: my-githubactions

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: windows-latest

    steps:
      - name: Print Hello Message
        run : echo "Hello, world from my_testing"
      - name: list content
        run : dir
      - name: systeminfo
        run: systeminfo