name: my-githubactions

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: windows-latest

    steps:
      - name: Print Hello Message
        run : echo "Hello, world from my_testing"
      - name: list content
        run : dir
      - name: clone my repo
        uses: actions/checkout@v1
      - name: pyton setup
        uses: actions/setup-python@v1
      - name: poetry-install
        uses: knowsuchagency/poetry-install@v1
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: briefcase_build
        run : briefcase build
      - name: list content
        run: dir build/helloworld/windows/app